### ISSUE TITLE
Not working in Ben Sur

### ISSUE THREAD

**Issue by pit5bul** [stevedat/HP-Elitebook-830-G6-Hackintosh#8]
Just installed it on my HP 830 Elitebook G6 but Webcam and Microphone not working.
Battery status always a 1%.

I have a full DDST.aml file, maybe we can work together

**Comment by stevedat** [comment]
> Just installed it on my HP 830 Elitebook G6 but Webcam and Microphone not working. Battery status always a 1%.
> 
> I have a full DDST.aml file, maybe we can work together

OK, Webcam could be vendor issue, but needs checking, Microphone not working is confirmed. You might alternatively use usc headset or bluetooth earphone to have that function. Jack 3.5 not recognised.
Battery shows for me, send me you ACPI files that you are using, I will have a look.

**Comment by pit5bul** [comment]
i have battery working , i patched the ddst.aml file, but it didnt work from the build.
I was talking about the internal microphone, i just tested it in windows to see, both camera and mic work fine, so it probably is OSX because cameras are detected fine in ioregistry and attached to the correct USB bus.

Here is my acpi patching. BTW do you fake PCI id to get the camera working ?

[ACPI.zip](https://github.com/stevedat/HP-Elitebook-830-G6-Hackintosh/files/7874701/ACPI.zip)

**Comment by stevedat** [comment]
> i have battery working , i patched the ddst.aml file, but it didnt work from the build. I was talking about the internal microphone, i just tested it in windows to see, both camera and mic work fine, so it probably is OSX because cameras are detected fine in ioregistry and attached to the correct USB bus.
> 
> Here is my acpi patching. BTW do you fake PCI id to get the camera working ?
> 
> [ACPI.zip](https://github.com/stevedat/HP-Elitebook-830-G6-Hackintosh/files/7874701/ACPI.zip)

Post EFI - https://drive.google.com/file/d/1PQMc-m0R72ikXJCheNfhMyJO36yUL0WF/view?usp=sharing
@pit5bul  you can try mine.

**Comment by VGerris** [comment]
thanks for sharing, it says cannot download because violating policy. perhaps mediafire, wetransfer, or the repo here? don't forget to remove serial and stuff. thanks!

**Comment by stevedat** [comment]
> thanks for sharing, it says cannot download because violating policy. perhaps mediafire, wetransfer, or the repo here? don't forget to remove serial and stuff. thanks!

https://mega.nz/file/1FcnCa5S#DVWYx0Nuf5QR5MijMmHJIU0_E0j18v4VBkKELZwQy0s

**Comment by VGerris** [comment]
thanks, it boots :). also more stable than my own. I had no battery but fixed that by adding ECenabler.kext and removing the ACPI battery patches for G3. Sleep is the same : it goes to sleep and then wakes up again.
Only thing not working otherwise is the webcam, any ideas on that ? shows up in hardware as HP HD (it's a Chicony), photoboot starts and I see the cam as hardware but get no picture. enabled in BIOS and privacy thing is off. no idea why it does not work. HDMI works too. Microphone does not , that's about it.
Thanks a lot for sharing, I keep messing :).

**Comment by stevedat** [comment]
> thanks, it boots :). also more stable than my own. I had no battery but fixed that by adding ECenabler.kext and removing the ACPI battery patches for G3. Sleep is the same : it goes to sleep and then wakes up again.
> Only thing not working otherwise is the webcam, any ideas on that ? shows up in hardware as HP HD (it's a Chicony), photoboot starts and I see the cam as hardware but get no picture. enabled in BIOS and privacy thing is off. no idea why it does not work. HDMI works too. Microphone does not , that's about it.
> Thanks a lot for sharing, I keep messing :).

Camera u might try mapping USB ports and set it internal usb. Hardware component

**Comment by VGerris** [comment]
hi, I changed it to internal. updated your kext, did not map otherwise.
Two cameras show, the view is just black. looks fine in ioreg, or?

I read it's hit or miss, did yours just work?
The mic seems a known problem too, it's a problem on Linux too, a bug with intel sof firmware loading that is fixed on some distros. perhaps that same firmware has to be loaded somehow.
Could file a bug at AppleHDA project perhaps. 
Kind of sucks. Then again, I have an external webcam with a mic, so that rounds it up.
If I have time I may try to do things the proper way, with patching from scratch, just not much time atm.

Thanks for the help and support, I will post if I find a solution.

![Screenshot 2022-01-16 at 15 43 30](https://user-images.githubusercontent.com/793993/149673237-55c0b83f-e393-4d93-9dde-842ccb474ba6.png)
.

**Comment by VGerris** [comment]
my attempt is here : https://github.com/VGerris/HP-Elitebook-830-G6-OSX86 . thanks for your help, I hope we can fix mic and webcam some day :)

**Comment by stevedat** [comment]
> my attempt is here : https://github.com/VGerris/HP-Elitebook-830-G6-OSX86 . thanks for your help, I hope we can fix mic and webcam some day :)

Intel i5-8365U, not same with mine is Intel i5-8265U (Whiskey Lake). If yours not the same, you might look at ACPI .aml some lacking or need changing, but if same, that would be fine. 
Mine jack 3.5 audio headset works but no audio recording, cannot use microphone. need s.o to modify the kext

**Comment by VGerris** [comment]
Hi,I have a i5-8365U whiskylake. You think it matters? Do you have the same hardware ids? I have the same with the jack, audio yes, no mic. Any idea how to fix that? I think some firmware has to be loaded like in Linux.

**Comment by pit5bul** [comment]
i think we have the windows hello cameras and the IR camera takes over...
while Steve has the normal without the IR cam.

**Comment by VGerris** [comment]
I was thinking the same :). So your cam does not work either? Perhaps we
can compare IOreg and modify some IDs, might work.

**Comment by stevedat** [comment]
> I was thinking the same :). So your cam does not work either? Perhaps we can compare IOreg and modify some IDs, might work.
> […](#)



> Hi,I have a i5-8365U whiskylake. You think it matters? Do you have the same hardware ids? I have the same with the jack, audio yes, no mic. Any idea how to fix that? I think some firmware has to be loaded like in Linux.

Same cpu so you just use my ACPI files, it would be okay.
Jack 3.5 no mic. no way fix now, I use usb headset, mic works.

**Comment by stevedat** [comment]
> > I was thinking the same :). So your cam does not work either? Perhaps we can compare IOreg and modify some IDs, might work.
> > […](#)
> 
> > Hi,I have a i5-8365U whiskylake. You think it matters? Do you have the same hardware ids? I have the same with the jack, audio yes, no mic. Any idea how to fix that? I think some firmware has to be loaded like in Linux.
> 
> Same cpu so you just use my ACPI files, it would be okay. Jack 3.5 no mic. no way fix now, I use usb headset, mic works. Another way is use iphone as input mic, but need some tricks :)

Linux, like Ubuntu should work out of the box. I used U and all things work like a charm, no issues at all.

**Comment by stevedat** [comment]
> I was thinking the same :). So your cam does not work either? Perhaps we can compare IOreg and modify some IDs, might work.
> […](#)

Both of you might have same camera vendor, which is different mine. Mine work on booting no need modification.
Just jack 3.5 micro, not working even correct layout ID for AppleALC. But if you MacOS versions below 11.3, use VoodooHDA.kext. Micro on jack 3.5 supported and works out of the box. AppleALC we need s.o to make changes and full support 830 G6

**Comment by VGerris** [comment]
ah I missed this. I run 12.1. Yes we seem to have different cams. Correct, mic should work but due to a bug it does not work in Ubuntu ( even need to change alsa conf to have sound at all ). there is a shady blob from intel that needs to be loaded.
I think the bug is fixed on Fedora and Arch, not in Ubuntu (many open bugs on launchpad). perhaps we have different audio too.
I use this laptop for work now, I might give VoodooHDA a try. I use a USB webcam with mic now so that pretty much solves all problem.
The only strange thing I have that is an issue is that after sleep, often network issues occur, like YouTube not working.
Otherwise the machine works great.

**Comment by pit5bul** [comment]
i tested on Ubuntu live and mic works great

**Comment by stevedat** [comment]
> ah I missed this. I run 12.1. Yes we seem to have different cams. Correct, mic should work but due to a bug it does not work in Ubuntu ( even need to change alsa conf to have sound at all ). there is a shady blob from intel that needs to be loaded.
> I think the bug is fixed on Fedora and Arch, not in Ubuntu (many open bugs on launchpad). perhaps we have different audio too.
> I use this laptop for work now, I might give VoodooHDA a try. I use a USB webcam with mic now so that pretty much solves all problem.
> The only strange thing I have that is an issue is that after sleep, often network issues occur, like YouTube not working.
> Otherwise the machine works great.

Great!
I see you find alternative to live with a non-native laptop running MacOS.
